### ISSUE TITLE
Question about morph

### ISSUE THREAD

**Issue by yuzewang1998** [jimtsai23/MorphFlow#1]
Hi,
Thanks for the great work! When I optimized the explicit representation of scenes Lego and Chair, I got two models like ```xxx.tar```. However, when I was ready to morph from Lego to Chair with the command in README, I got the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'morph_data/lego.pkl'
```
However, I don't find where the ```xxx.pkl``` is saved in the training stage. So I want to know, how can I get the ```xxx.pkl``` file? Is it converted from a ```xxx.tar``` file?

Looking forward to your reply!
Thank you

**Comment by yuzewang1998** [comment]
I guess the key ```['model_state_dict']``` of the ```lego.tar``` is the most part of ```lego.pkl```, which we need to input,  right?
Because the  ```model_state_dict```  has keys ```xyz_min, xyz_max, density, k0 (I guess it is the rgb)``` we want.

However, ```data_A['near']```,```data_A['far']```,```data_A['HW']```,```data_A['Hs']``` are also needed, and I cant find these keys anywhere( though I can get it from the original dataset ). So, I guess there's some way to generate the ```.pkl``` file, rather than extract it from the ```lego.tar``` file.  Could you please give me some help? 

Looking forward to your reply!
Thank you!

**Comment by yuzewang1998** [comment]
Oh, I found the solution! When we train the DVGO model, we should add the config '--export_fine_only', like the following:
```
python run.py --config confgis/nerf/chair.py --export_fine_only "chair"
```
Then, I got the ```chair.pkl``` file! The result is awesome! Am I doing the right thing?
![003](https://user-images.githubusercontent.com/34028809/231985127-6042f617-442e-43e5-8392-0b193e528f5a.png)

**Comment by jimtsai23** [comment]
Yes. The result is similar to ours. Have fun!

**Comment by yuzewang1998** [comment]
Thank you !
